examples/demo_meeg_timefreq_searchlight.m
mvpa/cosmo_balance_partitions.m
mvpa/cosmo_chunkize.m
mvpa/cosmo_index_unique.m
mvpa/cosmo_run_tests.m
tests/test_align.m
tests/test_balance_partitions.m
tests/test_dim_generalization_measure.m
tests/test_index_unique.m
tests/test_target_dsm_corr_measure.m

This PR makes balances partitions in the test sets the default.
@andycon would you mind taking a look please?

NF: support balanced test partitions

---

examples/demo_meeg_timeseries_classification.m
mvpa/cosmo_dim_generalization_measure.m
mvpa/cosmo_dim_slice.m
mvpa/cosmo_meeg_chan_neighbors.m
mvpa/cosmo_meeg_chantype.m
tests/test_cluster_neighborhood.m
tests/test_cross_neighborhood.m
tests/test_dim_slice.m
tests/test_interval_neighborhood.m
tests/test_meeg_chan_neighborhood.m
tests/test_publish_run_scripts.m
tests/test_searchlight.m

using cosmo_slice and cosmo_dim_prune instead

ENH: deprecate cosmo_dim_slice

---

mvpa/cosmo_spherical_neighborhood.m
tests/test_publish_run_scripts.m
tests/test_spherical_neighborhood.m

Thanks to #Gaetan Sanchez# for the report

BF+ACK: Remove .a.sdim in spherical neighborhood if present

---

mvpa/cosmo_fmri_dataset.m
tests/test_fmri_dataset.m

To be used with https://github.com/PyMVPA/PyMVPA/pull/431

NF: support PyMVPA fMRI dataset import

---

mvpa/cosmo_average_samples.m
tests/test_average_samples.m

Thanks to #Yuan Tao# for suggesting this feature

NF: support different .sa fields when computing average over samples

---

doc/source/thanks.rst
mvpa/cosmo_meeg_layout_collection.m

Thanks to Joscha Schmiedt# for pointing this out. See comment https://github.com/fieldtrip/fieldtrip/commit/a297d505daa7e817a77f3fb6625c16acd84aed68#commitcomment-18351186

ENH+ACK: support integer values for positions of channels. 

---

tests/test_montecarlo_cluster_stat.m

TST: add more variability to test with different dh values

---

tests/test_run_tests.m

Addresses issue with strange Octave 4.0.3 crash on Linux travis-ci when using complicated onCleanup(...) syntax where the argument is a curry-ed function handle [1]. Could not replicate this using Octave 4.0.3 on OSX.
[1] https://travis-ci.org/nno/CoSMoMVPA/builds/163436469
```
*** glibc detected *** /usr/bin/octave-cli: double free or corruption (!prev): 0x000000000409a050 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7da26)[0x2b8a8fb40a26]
/usr/lib/x86_64-linux-gnu/liboctinterp.so.3(_ZN12symbol_table7cleanupEv+0x7d)[0x2b8a8f21c01d]
/usr/lib/x86_64-linux-gnu/liboctinterp.so.3(+0xb486de)[0x2b8a8f24e6de]
/usr/lib/x86_64-linux-gnu/liboctinterp.so.3(_Z17clean_up_and_exitib+0x17)[0x2b8a8f250057]
/usr/lib/x86_64-linux-gnu/liboctinterp.so.3(octave_execute_interpreter+0xd1a) …
```

TST: simplify running commands sequentially in cleanup after test

---

mvpa/cosmo_map2meeg.m
mvpa/cosmo_meeg_dataset.m
mvpa/cosmo_show_progress.m
tests/test_meeg_io.m

BF: assume that timef (freq) data has trials along last dimension, but erp (timelock) data trails along first dimension

ENH: Eeglab/shiftdim freq

---

mvpa/cosmo_montecarlo_cluster_stat.m
mvpa/cosmo_parallel_get_nproc_available.m
mvpa/cosmo_parallel_get_progress_suffix.m
mvpa/cosmo_searchlight.m

I think it would be nice if more functions can run in parallel. The cluster stat is one of them

Parallel montecarlo cluster stat

---

doc/source/cimec2014.rst
doc/source/cimec2016.rst
doc/source/conf.py
doc/source/contribute.rst
doc/source/cosmo2013.rst
doc/source/documentation.rst
doc/source/ex_dataset_basics.rst
doc/source/ex_searchlight.rst
doc/source/get_started.rst
doc/source/index.rst
doc/source/prni2016.rst
doc/source/rhul2016.rst
doc/tools/matlab2rst.py
mvpa/cosmo_montecarlo_cluster_stat.m

WEB: fix links

---

mvpa/cosmo_montecarlo_cluster_stat.m
mvpa/cosmo_parallel_get_nproc_available.m
mvpa/cosmo_parcellfun.m
mvpa/cosmo_wtf.m
tests/test_montecarlo_cluster_stat.m
tests/test_parallel_get_nproc_available.m
tests/test_wtf.m

For parallel processing toolbox in Matlab < 2013b

NF: support for matlabpool

---

.travis.yml

Issue reported at http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3269

FIX: temporarily skip using official FieldTrip because it makes the build crash

---

mvpa/cosmo_correlation_measure.m
mvpa/cosmo_isequaln.m
mvpa/cosmo_unflatten.m
tests/test_isequaln.m

 msc/merged prs

---

mvpa/cosmo_tiedrank.m
tests/test_tiedrank.m

NF: cosmo_tiedrank

---

mvpa/cosmo_map2meeg.m
mvpa/cosmo_meeg_dataset.m
tests/test_meeg_io.m

Issue reported by #Evelyn Muschter#

ENH+ACK: add support for FieldTrip MEEG data structures without "dim" field

---

mvpa/cosmo_dissimilarity_matrix_measure.m
mvpa/cosmo_pdist.m

Fix documentation in pdist-related functions to reflect pdist returning the lower triangle of the dsm

Pdist doc fix

---

mvpa/cosmo_cartprod.m
mvpa/cosmo_check_external.m
mvpa/cosmo_oddeven_partitioner.m
tests/test_meeg_io.m
tests/test_oddeven_partitioner.m

- a little code cleanup
- bring odd-even partitioner in line with other partitioners

Small fixes

---

mvpa/cosmo_balance_partitions.m
mvpa/cosmo_check_partitions.m
tests/test_balance_partitions.m
tests/test_check_partitions.m

use sorted partition indices, or show a warning

---

mvpa/cosmo_check_partitions.m

Fix: Remove duplicate code in check_partitions. My bad for not doing this during review of last pr.

code fix for check partitions

---

examples/run_rsm_measure_searchlight.m

'RUN+SML: fixed a comment typo'

---

mvpa/cosmo_surficial_neighborhood.m

A corresponding change in surfing_circleROI.m [surfing toolbox] is also made.

add feature to select neighborhood nodes based on the total area (mm^2)
